### PR TITLE
feat: Catppuccin 0.2.0

### LINKED ISSUE #10: Update to Catppuccin 0.2.0
The color theme looks awesome! Are there any plans for a light theme?

### PR DESCRIPTION
**Pull request by quentinguidee**
*This PR is a WIP*:

- [x] This PR doesn't have Mocha, Macchiato and Frappé themes yet
- [x] The colorscheme in some languages is not yet at the expected level
- [x] Variants generator (one file like [this colors.json](https://github.com/catppuccin/xcode/blob/main/colors.json) could allow to generate all 4 variants at once)

## Latte ([New UI Preview enabled](https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/))
Capture d’écran, le 2022-08-01 à 20 49 21

## Latte (Old UI)
Capture d’écran, le 2022-08-01 à 20 50 42

(closes #10)

### CODE REVIEW

**Comment by nekowinston** [comment]
Happy to help out with this PR where possible 🙂

**Comment by quentinguidee** [comment]
@tiepp What would be the recommended way to generate all 4 palettes from this one? Use Kotlin and generate them before the build task? (I don't know exactly how to do this with gradle); Or a Python script (something like [here](https://github.com/catppuccin/xcode/blob/main/generate.py)) is OK for now? Or do you have a better idea?

**Comment by sgoudham** [comment]
Hi 👋 I'm researching info on jetbrains plugin development to help out with this port. I would greatly appreciate it if you @tiepp (or @quentinguidee) could kindly explain the significance of the `Catppuccin.xml`? I've watched a few videos on the editor schema and read the docs but I'm not sure on why exactly it's needed.

**Comment by quentinguidee** [comment]
> Hi 👋 I'm researching info on jetbrains plugin development to help out with this port. I would greatly appreciate it if you @tiepp (or @quentinguidee) could kindly explain the significance of the `Catppuccin.xml`? I've watched a few videos on the editor schema and read the docs but I'm not sure on why exactly it's needed.

Hi! The JSON file defines the colors for the UI only, while the XML file manages the colors for the code. It shouldn't be updated directly, but with Settings > Editor > Color Scheme

**Comment by nekowinston** [comment]
@sgoudham and I worked on a Deno generator for all four themes on the https://github.com/catppuccin/jetbrains/tree/v0.2.0 branch.
We only import `@catppuccin/palette` for now, and iterate over all four palettes:
https://github.com/catppuccin/jetbrains/blob/b476b4363a39063aab1df42508ed42423e45f3b2/main.ts#L13-L24

And export [four JSONs](https://github.com/catppuccin/jetbrains/tree/v0.2.0/src/main/resources/themes) with it:
https://github.com/catppuccin/jetbrains/blob/b476b4363a39063aab1df42508ed42423e45f3b2/main.ts#L403

We plan to figure out the rest of the setup, then push onto this PR branch, if that's alright.

I'm personally clueless about the whole XML and Kotlin stuff, I just hope this helps.

**Comment by sgoudham** [comment]
Hi @quentinguidee, I just want some more clarification on the highlighting for the editor XML, you mention that the XML shouldn't be edited directly, so should we go into `Settings > Editor > Color Scheme` and manually edit the colours... then export the XML? Thanks!

**Comment by quentinguidee** [comment]
> Hi @quentinguidee, I just want some more clarification on the highlighting for the editor XML, you mention that the XML shouldn't be edited directly, so should we go into `Settings > Editor > Color Scheme` and manually edit the colours... then export the XML? Thanks!

Yeah, or you can click "play" (in the JSON) and edit the Settings > Editor > Color Scheme directly it will update the XML automatically!

**Comment by jeffijoe** [comment]
It looks like the [`Puccinier`](https://github.com/catppuccin/toolbox#%EF%B8%8F-puccinier) tool from the [`catppuccin/toolbox`](https://github.com/catppuccin/toolbox) repo can help with the palette generation.

Super excited for this, the Latte theme is my favorite!

**Comment by sgoudham** [comment]
Just for visibility, the latest updates are happening on the [v0.2.0](https://github.com/catppuccin/jetbrains/tree/v0.2.0) branch! @nekowinston and I are chugging along with it. However, there's a lot of highlights to be improved/added 😅 

I think we're planning to rebase on top of this PR so that everyone gets credit for their work 👏

**Comment by tiepp** [comment]
I'm totally excited about all the buzz in this PR 👏🏼 Unfortunately I don't have the time to actively participate. But let me know whenever you hit a milestone and I'll happily create a release and publish an update

**Comment by sgoudham** [comment]
Glad to see that you're still around @tiepp, winston and I were actually wondering it's possible to transfer the project into a catppuccin organisation on the jetbrains marketplace? We're trying to make sure our ports going forward are author agnostic as possible as it reduces the single point of failure if they aren't around!

**Comment by tiepp** [comment]
Definitely possible, 👍 [I checked before uploading](https://github.com/catppuccin/jetbrains/issues/2). An org email didn't exist back then. Let me know what it is and I'll transfer

**Comment by nekowinston** [comment]
Much appreciated! @tiepp that would be `core@catppuccin.com`, please!

**Comment by tiepp** [comment]
@nekowinston can you send me the url to an actual account in the JB Marketplace/Hub , please
like this: https://plugins.jetbrains.com/author/d59a2b2d-f225-40de-9d09-6a5df667309a

**Comment by nekowinston** [comment]
Oh sorry for the misunderstanding; we've set up an Organization on the JB Marketplace: https://plugins.jetbrains.com/organizations/Catppuccin
My personal Account URL is this: https://plugins.jetbrains.com/author/4e4ac960-19ec-43bc-a83a-050750eb6620

Wouldn't it be easier if I add you as a member to the organization? I don't know if it would be possible for you to transfer it to the organization if you're a member.

**Comment by tiepp** [comment]
Yep, add me to the org please

**Comment by nekowinston** [comment]
I've just added you 🙂

**Comment by tiepp** [comment]
The UI is kinda confusing, can you admin me on the org? Seems I'm lacking permissions to add the plugin

**Comment by tiepp** [comment]
Seems the transfer was successful

**Comment by nekowinston** [comment]
Thank you!
> can you admin me on the org?
I've added you as an admin originally, glad you got it working. Have to agree that the UI feels clunky.

**Comment by sgoudham** [comment]
Update on the progress of the port, I've recently improved a lot of the highlights for the UI and the languages. @nekowinston and I are planning to release 2.0.0 at least by the end of the month! (or whenever 2022.2.3 comes out!)

Languages
- [x] Java
- [x] Python
- [x] Rust
- [x] XML
- [x] JSON
- [x] HTML
- [x] YAML
- [x] TOML
- [ ] CSS
- [ ] TS/JS
- [ ] Go
- [ ] C
- [ ] Markdown
  - Code blocks need to be improved but 95% of it looks good!

Of course, this port will always be in a "work-in-progress" as there are endless amounts of updates, other languages still need to be verified and there will be UI highlights that we will have missed due to the sheer number of them. But with the above checklist completed, it should be a _**lovely**_ experience for our users!

## Sneak Peek
Here's a sneak peek of Mocha 👀 on the new and old UIs! (The new UI is in preview so I think that's why the file tree doesn't seem to be darker!)

New UI:
image

Old UI:
image

**Comment by sgoudham** [comment]
👀 👀 👀 👀 👀 👀 👀 

image

**Comment by andreasgrafen** [comment]
uwu

**Comment by sgoudham** [comment]
For anyone wanting to try it now: Here you go!!! (GitHub doesn't allow `.jar` files so I've zipped it!)

[Catppuccin Theme-2.0.0.zip](https://github.com/catppuccin/jetbrains/files/9843596/Catppuccin.Theme-2.0.0.zip)

**Review by nekowinston — APPROVED** [review]

**Review by sgoudham — APPROVED** [review]
So... I guess this is it. 🎉 🎉 

Thanks to everyone for their hard work on this! @quentinguidee for the original PR, the lovely @nekowinston for the build system that generates the four flavours and of course, @tiepp for transferring the port to the Catppuccin organisation on the Jetbrains Marketplace!

Really happy to see this PR finally come to fruition and get merged. We actually decided to not go ahead with the alpha channel and just release on stable instead. Hopefully will get approved in the coming days!

This port still has some minor improvements coming its way but at least we got the major one out the door 😄

**Pull request merged**
